import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync,writeFileSync,mkdtempSync,existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { LocalTools } from '../src/main/services/localTools.ts';
import { Application } from '../src/main/services/application.ts';
import { ReplicaService } from '../src/main/services/replica.ts';
import { defaults } from '../src/shared/catalog.ts';
import { writeTaskZip } from '../src/main/services/taskZipWriter.ts';
import { engineModels } from '../src/shared/engineCatalog.ts';
import { KlingAdapter,engineEndpoint } from '../src/main/models/engineAdapters.ts';
import { HttpClient } from '../src/main/providers/http.ts';
import type { Snapshot } from '../src/shared/types.ts';
import { pageNumbers } from '../src/renderer/tools/pdf.ts';
const hash=(b:Buffer)=>createHash('sha256').update(b).digest('hex');
test('v128 旧一键生成调用链与上传 v124 一致，仅允许产品版本升级',()=>{
 for(const [path,digest] of Object.entries(JSON.parse(readFileSync('legacy-v124-sha256.json','utf8')))){
  let bytes=readFileSync(path);
  if(path==='src/shared/brand.ts'){
   assert.match(bytes.toString(),/version: "1\.4\.0"/);
   bytes=Buffer.from(bytes.toString().replace('version: "1.4.0"','version: "1.2.3"'));
  }
  assert.equal(hash(bytes),digest,path);
 }
});
test('v128 本地 MP4/MOV/MKV → MP3/WAV，中文路径、无音轨、错误文件、输出目录',async()=>{
 const root=mkdtempSync(join(tmpdir(),'中文工具-'));const tools=new LocalTools(()=>undefined);
 for(const extension of ['mp4','mov','mkv']){const source=join(root,'中文视频.'+extension);execFileSync('ffmpeg',['-nostdin','-v','error','-f','lavfi','-i','color=size=320x240:rate=25','-f','lavfi','-i','sine=frequency=440:sample_rate=44100','-t','1','-c:v','libx264','-c:a','aac',source]);for(const format of ['mp3','wav']){const r=await tools.audio(source,format);assert(existsSync(r.files[0]));const probe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-of','json',r.files[0]],{encoding:'utf8'}));assert.equal(probe.streams.length,1);assert.equal(probe.streams[0].codec_name,format==='mp3'?'mp3':'pcm_s16le');let opened='';await tools.open(r.folder,async p=>{opened=p;return '';});assert.equal(opened,r.folder);await assert.rejects(tools.open(r.folder,async()=> 'OS error'),/OS error/);}}
 const bad=join(root,'错误视频.mp4');writeFileSync(bad,'not a video');await assert.rejects(tools.audio(bad,'mp3'));const noAudio=join(root,'无声.mp4');execFileSync('ffmpeg',['-v','error','-f','lavfi','-i','color=size=64x64','-t','1','-c:v','libx264',noAudio]);await assert.rejects(tools.audio(noAudio,'wav'));await assert.rejects(tools.open(root,async()=>''));await assert.rejects(tools.audio(bad,'exe'));
});
test('v128 页码范围校验',()=>{assert.deepEqual(pageNumbers('',3),[1,2,3]);assert.deepEqual(pageNumbers('2-3,1,2',3),[1,2,3]);assert.deepEqual(pageNumbers('2-3',3),[2,3]);for(const s of ['0','4','3-1','x','1,'])assert.throws(()=>pageNumbers(s,3));});
function setup(){const root=mkdtempSync(join(tmpdir(),'replica-'));let calls=0;const app=new Application(root,{isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s),decryptString:b=>b.toString()},async()=>({width:720,height:1280,duration:5,fps:25}),()=>{},()=>{},async()=>{calls++;throw new Error('No network in offline tests');});for(const providerId of ['alibaba','volcengine','kling'])app.credentials.save({name:providerId,providerId,workspaceId:'ws-test',region:'cn-beijing',key:'offline-fixture-key'});return {app,root,calls:()=>calls};}
test('v128 独立任务包导入、切换、恢复、确认失效、去重与旧服务隔离',async()=>{const {app,root,calls}=setup();try{const svc=new ReplicaService(app);const manifest={schema:'chigetang.replica',version:'1.0',name:'测试复刻',assets:[],segments:['wan-safe','seedance15','kling26'].map((model_id,i)=>({id:'G00'+(i+1),model_id,prompt:'一杯咖啡，固定镜头',params:{},bindings:[]}))};const m=join(root,'manifest.json');writeFileSync(m,JSON.stringify(manifest));const zip=join(root,'task.zip');await writeTaskZip(zip,[{path:'manifest.json',file:m}]);let s=await svc.importZip(zip);assert.equal(s.segments.length,3);assert.equal(svc.list().length,1);s=await svc.preflight(s.id);assert(s.segments.every(x=>!x.issue),JSON.stringify(s.segments));s=await svc.confirm(s.id,s.revision);assert.equal(s.confirmed,true);const d={...s.segments[0].draft,prompt:'编辑后的提示词'};s=svc.update(s.id,'G001',d);assert.equal(s.confirmed,false);await assert.rejects(svc.submit(s.id));s=await svc.preflight(s.id);s=await svc.confirm(s.id,s.revision);s=await svc.submit(s.id);assert.equal(s.taskIds.length,3);assert.equal((await svc.submit(s.id)).taskIds.length,3);assert.equal((await new ReplicaService(app).importZip(zip)).state,'submitted');assert.equal(app.tasks.list({page:1,pageSize:20}).total,3);assert.equal(calls(),0);for(const id of s.taskIds)assert.equal(app.tasks.get(id).status,'Queued');}finally{app.close();}});
test('v128 可灵提交参数、单次调用、轮询状态与官方域名',async()=>{const model=engineModels.find(m=>m.id==='kling26')!;let body:any;let requests=0;const http=new HttpClient(async(_u,options)=>{requests++;body=options?.body?JSON.parse(String(options.body)):body;return new Response(JSON.stringify({code:0,data:options?.method==='POST'?{task_id:'task-123'}:{task_status:'succeed',task_result:{videos:[{url:'https://example.com/test.mp4'}]}}}),{status:200});});const adapter=new KlingAdapter(http,async()=> 'saved');const {app}=setup();try{const s:Snapshot={draft:{...app.newDraft(),modelId:model.id,params:defaults(model),prompt:'测试',assets:[]},model,provider:app.providers().find(p=>p.id==='kling')!,account:app.credentials.list().find(a=>a.providerId==='kling')!,assets:[],price:model.price,estimatedCost:{amount:null,currency:'USD',kind:'unknown',note:''},appVersion:'1.2.8',createdAt:''};adapter.validateInput(s);assert.equal(await adapter.submitTask(s,'key',[]),'task-123');assert.equal(body.model_name,'kling-v2-6');assert.equal(body.sound,'off');assert.equal(body.duration,'5');assert.equal((await adapter.getTaskStatus(s,'key','task-123')).status,'succeeded');assert.equal(requests,2);assert.throws(()=>engineEndpoint({...s,account:{...s.account,endpoint:'https://example.com'}}));}finally{app.close();}});
test('v128 可灵/Seedance 1.5/2.5 模拟云端完整生命周期、下载真实 MP4',async()=>{
 for(const modelId of ['kling26','seedance15','seedance25']){const root=mkdtempSync(join(tmpdir(),'engine-cycle-'));let submits=0;let polls=0;const video=readFileSync('tests/fixtures/sample.mp4');const app=new Application(root,{isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s),decryptString:b=>b.toString()},async()=>({width:720,height:1280,duration:5}),()=>{},()=>{},async(url,options)=>{
 const u=String(url);if(u==='https://example.com/result.mp4')return new Response(video,{headers:{'content-type':'video/mp4'}});
 if(options?.method==='POST'){submits++;return new Response(JSON.stringify(modelId==='kling26'?{code:0,data:{task_id:'cloud-task'}}:{id:'cloud-task'}));}
 polls++;return new Response(JSON.stringify(modelId==='kling26'?{code:0,data:{task_status:'succeed',task_result:{videos:[{url:'https://example.com/result.mp4'}]}}}:{status:'succeeded',content:{video_url:'https://example.com/result.mp4'}}));
 });try{const model=app.models().find(m=>m.id===modelId)!;const account=app.credentials.save({name:'fixture',providerId:model.providerId,region:'cn-beijing',key:'fixture-key'});const t=await app.tasks.create({...app.newDraft(),modelId,accountId:account.id,params:defaults(model),prompt:'固定镜头测试'},'lifecycle');const signal=new AbortController().signal;await app.tasks.run(t,signal);let latest=app.tasks.get(t.id);if(latest.status!=='Completed')await app.tasks.run(latest,signal);latest=app.tasks.get(t.id);assert.equal(latest.status,'Completed',latest.error||'');assert.equal(submits,1);assert(polls>=1);assert.deepEqual(readFileSync(latest.outputPath!),video);}finally{app.close();}}
});
test('v128 新 WAN 保留 14.8 秒音频，超限阻止且旧链路保持原行为',async()=>{const {app,root}=setup();try{const source=join(root,'完整参考.wav');execFileSync('ffmpeg',['-v','error','-f','lavfi','-i','sine=frequency=440','-t','14.8',source]);const imported=await app.assets.import(source,false);app.assets.probe=async()=>({duration:14.8,sampleRate:44100,channels:1});const m=app.models().find(m=>m.id==='wan-safe')!;const draft={...app.newDraft(),modelId:m.id,params:defaults(m),prompt:'参考音频',assets:[{assetId:imported.asset.id,role:'reference_audio' as const}]};const t=await app.tasks.create(draft,'audio-full');assert.equal(t.snapshot.assets[0].id,imported.asset.id);assert.equal(t.snapshot.assets[0].duration,14.8);app.assets.probe=async()=>({duration:20,sampleRate:44100,channels:1});await assert.rejects(app.tasks.create(draft,'audio-too-long'));}finally{app.close();}});
test('v128 数据升级保留已有草稿和账户，备份可读，重复启动不重复迁移',()=>{const {app,root}=setup();const draft=app.newDraft();draft.prompt='已有中文草稿';app.drafts.save(draft);const ids=app.credentials.list().map(a=>a.id);app.close();const vault={isEncryptionAvailable:()=>true,encryptString:(s:string)=>Buffer.from(s),decryptString:(b:Buffer)=>b.toString()};const reopen=()=>new Application(root,vault,async()=>({}),()=>{},()=>{});const next=reopen();const backup=next.db.get<string>('v128-backup','');assert(existsSync(backup));assert.equal(next.drafts.get(draft.draftId!).prompt,'已有中文草稿');assert.deepEqual(next.credentials.list().map(a=>a.id),ids);next.close();const again=reopen();assert.equal(again.db.get('v128-backup',''),backup);assert.equal(again.drafts.get(draft.draftId!).prompt,draft.prompt);again.close();});
test('v128 预检锁定期间禁止修改、确认及重复预检，已提交轮次不可重预检',async()=>{const {app}=setup();try{const svc=new ReplicaService(app);const model=app.models().find(m=>m.id==='wan-safe')!;const s=svc.save({id:'lock-test',name:'lock',revision:1,confirmed:false,state:'ready',taskIds:[],segments:[{id:'G001',draft:{...app.newDraft(),modelId:model.id,params:defaults(model),prompt:'test'}}]});const pending=svc.preflight(s.id);assert.throws(()=>svc.update(s.id,'G001',s.segments[0].draft),/处理中/);const confirming=svc.confirm(s.id,1),checking=svc.preflight(s.id);await Promise.all([assert.rejects(confirming,/处理中/),assert.rejects(checking,/处理中/)]);await pending;const checked=svc.get(s.id);checked.state='submitted';svc.save(checked);await assert.rejects(svc.preflight(s.id),/不可预检/);}finally{app.close();}});
test('v128 密钥不可用时提交失败仍保持可编辑，不锁死离线任务',async()=>{const {app}=setup();try{const svc=new ReplicaService(app);const model=app.models().find(m=>m.id==='wan-safe')!;let s=svc.save({id:'no-key',name:'no-key',revision:1,confirmed:false,state:'ready',taskIds:[],segments:[{id:'G001',draft:{...app.newDraft(),modelId:model.id,params:defaults(model),prompt:'test'}}]});s=await svc.preflight(s.id);await svc.confirm(s.id,1);app.credentials.getKey=()=>{throw new Error('密钥不可用');};await assert.rejects(svc.submit(s.id),/密钥不可用/);assert.equal(svc.get(s.id).state,'ready');assert.equal(svc.get(s.id).taskIds.length,0);}finally{app.close();}});
