import { useState } from 'react';
import { api } from '../store.ts';
import { pageNumbers,renderPdfPages } from '../tools/pdf.ts';
function ToolCard({kind}:{kind:'audio'|'pdf'}){
 const [path,setPath]=useState(''),[directory,setDirectory]=useState(''),[format,setFormat]=useState(kind==='audio'?'mp3':'png'),[range,setRange]=useState(''),[mode,setMode]=useState('all'),[state,setState]=useState('待处理'),[error,setError]=useState(''),[folder,setFolder]=useState('');
 const busy=state==='处理中';function choose(path:string){setPath(path);setState('待处理');setError('');setFolder('');}
 async function start(){if(busy||!path)return;setState('处理中');setError('');setFolder('');let job:string|undefined;let pdf:import('pdfjs-dist').PDFDocumentProxy|undefined;
 try{if(kind==='audio'){const r=await api<{folder:string}>('tools.audio',{path,format,directory});setFolder(r.folder);}else{
 const lib=await import('pdfjs-dist/legacy/build/pdf.mjs');lib.GlobalWorkerOptions.workerSrc=(await import('pdfjs-dist/legacy/build/pdf.worker.min.mjs?url')).default;
 const bytes=await api<Uint8Array>('tools.pdfRead',{path});pdf=await lib.getDocument({data:new Uint8Array(bytes),cMapUrl:new URL('pdf/cmaps/',document.baseURI).href,cMapPacked:true,standardFontDataUrl:new URL('pdf/standard_fonts/',document.baseURI).href,wasmUrl:new URL('pdf/wasm/',document.baseURI).href,isEvalSupported:false}).promise;
 const pages=pageNumbers(mode==='all'?'':range,pdf.numPages);if(mode==='range'&&!range.trim())throw new Error('请填写指定页码');const r=await api<{id:string}>('tools.pdfStart',{path,format,directory});job=r.id;
 await renderPdfPages(pdf,pages,format as 'png'|'jpg',()=>document.createElement('canvas'),async(page,bytes)=>{await api('tools.pdfPage',{id:job,page,bytes});});const result=await api<{folder:string}>('tools.pdfFinish',{id:job,success:true});job=undefined;setFolder(result.folder);
 }setState('完成');}catch(e){setError(String(e));setState('失败');}finally{if(job)await api('tools.pdfFinish',{id:job,success:false}).catch(()=>{});await pdf?.destroy().catch(()=>{});}}
 return <section className="batch-card local-tool"><h2>{kind==='audio'?'视频转音频':'PDF 转图片'}</h2><fieldset disabled={busy}><div className="tool-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy&&e.dataTransfer.files[0])choose(window.aiVideo.filePath(e.dataTransfer.files[0]));}}><p>{path||'选择文件，或拖入本地文件'}</p><button onClick={()=>void api<string|null>('tools.select',{kind}).then(p=>{if(p)choose(p);}).catch(e=>setError(String(e)))}>选择{kind==='audio'?'视频':'PDF'}</button><small>{kind==='audio'?'MP4 / MOV / MKV':'每页独立输出，200 DPI'}</small></div><div className="tool-fields"><label>输出格式<select value={format} onChange={e=>setFormat(e.target.value)}>{(kind==='audio'?['mp3','wav']:['png','jpg']).map(f=><option key={f} value={f}>{f.toUpperCase()}</option>)}</select></label>{kind==='pdf'&&<label>页面<select value={mode} onChange={e=>setMode(e.target.value)}><option value="all">全部页面</option><option value="range">指定页码范围</option></select></label>}{kind==='pdf'&&mode==='range'&&<label>页码<input value={range} onChange={e=>setRange(e.target.value)} placeholder="例如 1-3,5"/></label>}</div><p>输出目录：{directory||'原文件同目录（独立结果文件夹）'}</p><button onClick={()=>void api<string|null>('dialog.directory').then(p=>{if(p)setDirectory(p);}).catch(e=>setError(String(e)))}>选择输出目录</button>{directory&&<button onClick={()=>setDirectory('')}>使用原目录</button>}</fieldset><div className="tool-actions"><button className="primary" disabled={!path||busy} onClick={()=>void start()}>开始处理</button><span role="status">{state}</span>{folder&&<button onClick={()=>void api('tools.open',{folder}).catch(e=>setError(String(e)))}>打开输出目录</button>}</div>{error&&<p role="alert" className="notice warning">{error}</p>}</section>;
}
export function ToolsPage(){return <div className="tools-page"><h1>小工具</h1><p>本地处理，无需 API 账户。</p><div className="tools-grid"><ToolCard kind="audio"/><ToolCard kind="pdf"/></div></div>;}
