import { createServer } from 'node:http';
import { readFileSync,writeFileSync,mkdirSync,mkdtempSync } from 'node:fs';
import { join,resolve,extname } from 'node:path';
import { tmpdir } from 'node:os';
import { createRequire } from 'node:module';
import { Application } from '../src/main/services/application.ts';
import { LocalTools } from '../src/main/services/localTools.ts';
import { ReplicaService } from '../src/main/services/replica.ts';
const require=createRequire(import.meta.url);const {chromium}=require(process.env.PLAYWRIGHT_MODULE||(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'):'playwright'));
const root=mkdtempSync(join(tmpdir(),'ctg-browser-data-'));const app=new Application(root,{isEncryptionAvailable:()=>false,encryptString:()=>{throw new Error('No vault');},decryptString:()=>{throw new Error('No vault');}},async()=>({width:720,height:1280,duration:5}),()=>{},()=>{});const tools=new LocalTools(()=>undefined);const replica=new ReplicaService(app);const errors:string[]=[];
const server=createServer(async(req,res)=>{try{if(req.url==='/rpc'){let body='';for await(const c of req)body+=c;const {action,p={}}=JSON.parse(body);let value:unknown;switch(action){case 'bootstrap':value=app.bootstrap();break;case 'draft.new':value=app.newDraft();break;case 'draft.save':value=app.drafts.save(p);break;case 'draft.list':value=app.drafts.list();break;case 'tasks.list':value=app.tasks.list(p);break;case 'tasks.estimate':value=app.tasks.estimate(p);break;case 'assets.get':value=app.assets.get(p.id);break;case 'replica.list':value=replica.list();break;case 'tools.select':value=p.kind==='pdf'?resolve('tests/fixtures/中文多页.pdf'):resolve('tests/fixtures/sample.mp4');break;case 'tools.pdfRead':value=Array.from(await tools.pdfRead(p.path));break;case 'tools.pdfStart':value=await tools.pdfStart(p.path,p.format,p.directory||root);break;case 'tools.pdfPage':value=await tools.pdfPage(p.id,p.page,Uint8Array.from(Object.values(p.bytes)));break;case 'tools.pdfFinish':value=await tools.pdfFinish(p.id,p.success);break;case 'tools.audio':value=await tools.audio(p.path,p.format,p.directory);break;case 'tools.open':value=await tools.open(p.folder,async()=> '');break;case 'folders.list':value=[];break;default:value=null;}
res.setHeader('Content-Type','application/json');res.end(JSON.stringify({ok:true,data:value}));return;}
const pathname=new URL(req.url!,'http://localhost').pathname;const path=join(resolve('dist/renderer'),decodeURIComponent(pathname==='/'?'/index.html':pathname));const mime:Record<string,string>={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.wasm':'application/wasm'};res.setHeader('Content-Type',mime[extname(path)]||'application/octet-stream');res.end(readFileSync(path));}catch(e){res.statusCode=500;res.end(JSON.stringify({ok:false,error:String(e)}));}});
await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const address=server.address() as {port:number};
console.log('Launching browser');const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu'],headless:true,timeout:20000});const page=await browser.newPage({viewport:{width:1440,height:960}});page.on('pageerror',(e:Error)=>errors.push(String(e)));page.on('console',(m:any)=>{if(m.type()==='error')errors.push(m.text());});
await page.addInitScript(()=>{(window as any).aiVideo={invoke:async(action:string,p:unknown)=>{const r=await (await fetch('/rpc',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,p})})).json();if(!r.ok)throw new Error(r.error);return r.data;},onChange:()=>()=>{},onNavigate:()=>()=>{},filePath:()=>''};});
try{console.log('Opening built app');await page.goto('http://127.0.0.1:'+address.port);await page.getByRole('heading',{name:'一键生成',exact:false}).waitFor();console.log('App loaded');await page.getByRole('button',{name:'小工具',exact:true}).click();await page.getByRole('heading',{name:'PDF 转图片'}).waitFor();const card=page.locator('.local-tool').filter({has:page.getByRole('heading',{name:'PDF 转图片'})});await card.getByRole('button',{name:'选择PDF'}).click();await card.getByRole('button',{name:'开始处理'}).click();await card.getByRole('status').filter({hasText:'完成'}).waitFor({timeout:60000});await card.getByRole('button',{name:'打开输出目录'}).click();
mkdirSync('docs/v128',{recursive:true});await page.screenshot({path:'docs/v128/tools-wide.png',fullPage:true});await page.setViewportSize({width:1050,height:800});await page.screenshot({path:'docs/v128/tools-narrow.png',fullPage:true});
await page.getByRole('button',{name:'一键复刻',exact:true}).click();await page.screenshot({path:'docs/v128/replica-narrow.png',fullPage:true});await page.getByRole('button',{name:'视频生成',exact:true}).click();await page.getByLabel('视频引擎',{exact:true}).selectOption('kling');await page.screenshot({path:'docs/v128/generate-kling-narrow.png',fullPage:true});
if(errors.length)throw new Error(errors.join('\n'));console.log('PASS browser: real PDF worker, local resources, convert/open handler, 1440/1050 screenshots, engine switch, no console/page errors');
}catch(e){console.error(errors);console.error(await page.locator('body').innerText().catch(()=>''));throw e;}finally{await browser.close();server.close();app.close();}
